# Generated by Django 6.0.5 on 2026-06-30 18:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Prefer not to say')], max_length=10),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='height_cm',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Height in centimetres', null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='weight_kg',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Weight in kilograms', null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(250)]),
        ),
    ]
