# Generated by Django 6.0.5 on 2026-06-09 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(choices=[('national_id', 'National ID'), ('passport', 'Passport'), ('alien_id', 'Alien ID')], max_length=20)),
                ('id_number', models.CharField(max_length=50)),
                ('front_image', models.FileField(blank=True, null=True, upload_to='verification/%Y/%m/')),
                ('back_image', models.FileField(blank=True, null=True, upload_to='verification/%Y/%m/')),
                ('selfie_image', models.FileField(blank=True, null=True, upload_to='verification/%Y/%m/')),
                ('provider', models.CharField(default='smile_identity', max_length=50)),
                ('provider_ref', models.CharField(blank=True, max_length=100)),
                ('provider_result', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('manual_review', 'Manual Review')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'identity_verifications',
            },
        ),
    ]
