# Generated by Django 6.0.5 on 2026-06-09 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donors', '0001_initial'),
        ('hospitals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=10)),
                ('required_donations', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'badges',
                'ordering': ['required_donations'],
            },
        ),
        migrations.CreateModel(
            name='DonationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_type', models.CharField(choices=[('whole_blood', 'Whole Blood'), ('platelet', 'Platelet'), ('plasma', 'Plasma'), ('organ', 'Organ')], max_length=20)),
                ('donation_date', models.DateField()),
                ('credits_awarded', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_donations', to=settings.AUTH_USER_MODEL)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='donors.donorprofile')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='hospitals.hospitalprofile')),
            ],
            options={
                'db_table': 'donation_records',
                'ordering': ['-donation_date'],
            },
        ),
        migrations.CreateModel(
            name='CreditLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('earn', 'Earned'), ('redeem', 'Redeemed'), ('expire', 'Expired'), ('bonus', 'Bonus')], max_length=10)),
                ('amount', models.IntegerField()),
                ('balance_after', models.IntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_ledger', to='donors.donorprofile')),
                ('related_donation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gamification.donationrecord')),
            ],
            options={
                'db_table': 'credit_ledger',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonorBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.badge')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to='donors.donorprofile')),
            ],
            options={
                'db_table': 'donor_badges',
                'unique_together': {('donor', 'badge')},
            },
        ),
    ]
