# Generated by Django 6.0.5 on 2026-06-09 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_role', models.CharField(blank=True, max_length=30)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('password_change', 'Password Change'), ('donor_register', 'Donor Registered'), ('donor_profile_update', 'Donor Profile Updated'), ('donor_delete', 'Donor Account Deleted'), ('hospital_register', 'Hospital Registered'), ('hospital_approve', 'Hospital Approved'), ('hospital_reject', 'Hospital Rejected'), ('donor_search', 'Donor Search'), ('contact_initiated', 'Contact Request Initiated'), ('contact_accepted', 'Contact Request Accepted'), ('contact_declined', 'Contact Request Declined'), ('donation_recorded', 'Donation Recorded'), ('credits_redeemed', 'Credits Redeemed'), ('payment_initiated', 'Payment Initiated'), ('payment_success', 'Payment Successful'), ('admin_action', 'Admin Action')], max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('endpoint', models.CharField(blank=True, max_length=255)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('metadata', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_in_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
