# Generated by Django 6.0.5 on 2026-06-09 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=255)),
                ('facility_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('ngo', 'NGO'), ('blood_bank', 'Blood Bank')], max_length=20)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('year_established', models.PositiveIntegerField(blank=True, null=True)),
                ('address', models.TextField()),
                ('county', models.CharField(max_length=100)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('subscription_tier', models.CharField(choices=[('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise'), ('public', 'Public Hospital')], default='starter', max_length=20)),
                ('subscription_status', models.CharField(default='inactive', max_length=20)),
                ('subscription_expires', models.DateTimeField(blank=True, null=True)),
                ('search_quota', models.PositiveIntegerField(default=0)),
                ('search_limit', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_profile', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_hospitals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hospital_profiles',
            },
        ),
        migrations.CreateModel(
            name='HospitalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('registration', 'Registration Certificate'), ('license', 'Operating License'), ('tax', 'Tax Compliance Certificate'), ('representative', 'Representative ID')], max_length=20)),
                ('file', models.FileField(upload_to='hospital_docs/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='hospitals.hospitalprofile')),
            ],
            options={
                'db_table': 'hospital_documents',
            },
        ),
        migrations.CreateModel(
            name='HospitalStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='hospitals.hospitalprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_staff', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hospital_staff',
            },
        ),
    ]
